version: '3.1'
services:
  db:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_PASSWORD: p
      POSTGRES_USER: helpinghands
      POSTGRES_DB: helpinghands
    ports:
      - "5430:5432"
    volumes:
      - ./backend/migrations:/docker-entrypoint-initdb.d/